"""add name to leaders table

Revision ID: 77c26d4c8ca9
Revises: e5ffa2bb3ad7
Create Date: 2025-04-08 20:15:03.030975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c26d4c8ca9'
down_revision: Union[str, None] = 'e5ffa2bb3ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaders', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'leaders', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaders', type_='unique')
    op.drop_column('leaders', 'name')
    # ### end Alembic commands ###
