version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "80:80"
    networks:
      - backend_rl-network
    restart: unless-stopped

networks:
  backend_rl-network:
    external: true
