version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./src/api/.env.api
      - ./src/bot/.env.bot
    networks:
      - rl-network

networks:
  rl-network:
    driver: bridge


