"""create esia_tokens tables

Revision ID: 54ec647d036c
Revises: aa9f9fd4d105
Create Date: 2025-04-07 15:08:26.732620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54ec647d036c'
down_revision: Union[str, None] = 'aa9f9fd4d105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_id', table_name='admins')
    op.drop_index('ix_admins_tg_id', table_name='admins')
    op.drop_table('admins')
    op.add_column('esia_tokens', sa.Column('token', sa.String(), nullable=False))
    op.alter_column('esia_tokens', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('esia_tokens', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_esia_tokens_id'), 'esia_tokens', ['id'], unique=False)
    op.create_unique_constraint(None, 'esia_tokens', ['user_id'])
    op.drop_column('esia_tokens', 'expires_at')
    op.drop_column('esia_tokens', 'created_at')
    op.drop_column('esia_tokens', 'updated_at')
    op.drop_column('esia_tokens', 'access_token')
    op.drop_column('esia_tokens', 'is_active')
    op.drop_column('esia_tokens', 'refresh_token')
    op.drop_index('ix_users_esia_token', table_name='users')
    op.drop_column('users', 'esia_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('esia_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_esia_token', 'users', ['esia_token'], unique=True)
    op.add_column('esia_tokens', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('esia_tokens', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('esia_tokens', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('esia_tokens', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('esia_tokens', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('esia_tokens', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'esia_tokens', type_='unique')
    op.drop_index(op.f('ix_esia_tokens_id'), table_name='esia_tokens')
    op.alter_column('esia_tokens', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('esia_tokens', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('esia_tokens', 'token')
    op.create_table('admins',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    op.create_index('ix_admins_tg_id', 'admins', ['tg_id'], unique=True)
    op.create_index('ix_admins_id', 'admins', ['id'], unique=False)
    # ### end Alembic commands ###
